name: "First workflow"
on: [push]
jobs:
  helloworld:
    runs-on: [self-hosted]
    steps:
      - name: "Hello world action step"
        run: echo "Hello world! First runner workflow"
      - name: "Ok Bye! exit"
        run: exit 0